### ISSUE TITLE
bug?

### ISSUE THREAD

**Issue by plonolp** [tomhallam/Blurr#2]
can not work on IE9+,no blur effect

**Comment by tomhallam** [comment]
Hi there,

Can you provide a screenshot please?

**Comment by plonolp** [comment]
I  run the offical demo.in chrome and firefox,it is ok,but in ie11,there is no flur effect.
I just change the jquery.js like below
<script src="../dist/jquery-1.7.2.min.js"></script>
<script src="../dist/jquery.blurr.js"></script>
my os is windows 7 professional 64,and ie is 11,the windows and ie is Chinese edition.
i cannot upload the screenshot, can you give me a email?
thanks

**Comment by tomhallam** [comment]
You can attach images in the comment section of this page, you can drag and drop them from your desktop into the message. I'd rather not provide my email publicly.

Thanks

**Comment by plonolp** [comment]
I see, in IE 9+ the jquery version must be 1.9+,but in chrome and firefox,jquery1.7 and 1.8 is ok
Thanks

**Comment by tomhallam** [comment]
Oh right! Thanks for the report, I will update the documentation.
